# Generated by Django 4.2.16 on 2024-12-13 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0003_ingredient_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='cooked_weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1, message='Вес приготовленного продукта должен быть положительным.')]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1, message='Стоимость должна быть больше 0')]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='raw_weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1, message='Сырой вес должен быть положительным числом.')]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Имя не должно содержать спецсимволов', regex='^[A-Za-zА-Яа-яёЁ\\s0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(message='Рецепт не должен содержать специальных символов.', regex='^[A-Za-zА-Яа-яёЁ\\s0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='conversion_to_grams',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1, 'Коэффициент преобразования в граммы должен быть не меньше нуля.')]),
        ),
    ]
