# Generated by Django 4.2.16 on 2024-12-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0004_alter_ingredient_cooked_weight_alter_ingredient_cost_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_unit_per_user'),
        ),
    ]
