# Generated by Django 4.2.16 on 2024-12-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0005_unit_unique_unit_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
