# Generated by Django 4.2.16 on 2024-11-15 00:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Name should be a string value.', regex='^[A-Za-zА-Яа-яёЁ\\s]+$')])),
                ('raw_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0.1, message='Raw weight must be a positive number.')])),
                ('cooked_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0.1, message='Cooked weight must be a positive number.')])),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0.1, message='Cost must be a positive number.')])),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(message='Title should be a string value.', regex='^[A-Za-zА-Яа-яёЁ\\s]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_catalog.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_catalog.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipe_catalog.RecipeIngredient', to='recipe_catalog.ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
    ]
