"""Template names"""
INDEX_TEMPLATE_NAME = 'recipe_catalog/index.html'
RECIPE_TEMPLATE_NAME = 'recipe_catalog/recipe.html'
ABOUT_TEMPLATE_NAME = 'recipe_catalog/about-us.html'
REGISTER_TEMPLATE_NAME = 'recipe_catalog/registration.html'
LOGIN_TEMPLATE_NAME = 'recipe_catalog/login.html'
ADD_RECIPE_TEMPLATE_NAME = 'recipe_catalog/add-recipe.html'
ADD_INGREDIENT_TEMPLATE_NAME = 'recipe_catalog/add_ingredient.html'
MY_RECIPES_TEMPLATE_NAME = 'recipe_catalog/my_recipes.html'
ADD_INGREDIENT_TO_RECIPE_TEMPLATE_NAME = 'recipe_catalog/add_ingredient_to_recipe.html'
EDIT_RECIPE_TEMPLATE_NAME = 'recipe_catalog/edit_recipe.html'
MANAGE_RECIPIES_TEMPLATE_NAME = 'recipe_catalog/manage_recipes.html'
DELETE_INGREDIENT_TEMPLATE_NAME = 'recipe_catalog/delete_ingredient.html'
EDIT_INGREDIENT_TEMPLATE_NAME = 'recipe_catalog/edit_ingredient.html'
EDIT_INGREDIENT_FORM_TEMPLATE_NAME = 'recipe_catalog/edit_ingredient_form.html'
