version: '3.8'

services:
  django:
    build: .
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./static:/app/static 
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=recipe_project.settings

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static  
    ports:
      - "80:80"
    depends_on:
      - django
